name: 🤖 PR suites
on:
  pull_request:
  pull_request_review:
    types: [submitted]

env:
  JOBS_NAME: '[ "ci" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.83.0
      - uses: taiga-family/ci/actions/setup/variables@v1.83.0
      - id: matrix
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        run: echo "value=$JOBS_NAME" >> $GITHUB_OUTPUT

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: taiga-family/ci/actions/run/wait-job@v1.83.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.83.0
      - uses: taiga-family/ci/actions/setup/variables@v1.83.0
      - uses: taiga-family/ci/actions/auto/approve/double@v1.83.0
        continue-on-error: true
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: taiga-family/ci/actions/run/merge@v1.83.0
        continue-on-error: true
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  label-when-approved:
    if: github.event.review.state == 'approved'
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.83.0
      - uses: taiga-family/ci/actions/setup/variables@v1.83.0
      - uses: taiga-family/ci/actions/auto/label-when-approved@v1.83.0
        continue-on-error: true
        with:
          approvals: 2
          token: ${{ secrets.GITHUB_TOKEN }}

  assign-author:
    name: PR author as an assignee
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.83.0
      - uses: taiga-family/ci/actions/setup/variables@v1.83.0
      - uses: toshimaru/auto-author-assign@v2.1.1
        continue-on-error: true
        with:
          repo-token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  label-version:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.83.0
      - uses: taiga-family/ci/actions/setup/variables@v1.83.0
      - uses: taiga-family/ci/actions/run/node-info@v1.83.0
        id: nodejs-workspace
      - uses: actions-ecosystem/action-add-labels@v1
        continue-on-error: true
        with:
          labels: v${{ steps.nodejs-workspace.outputs.root-package-major-version }}

concurrency:
  group: auto-approve-${{ github.head_ref }}
  cancel-in-progress: true
